"""export.py — render a report / checklist / guide to Markdown. Stdlib only.

Exports are the shareable artifact (hand to a shop, post to a forum, keep for a
sale). VIN/plate are redacted by default; pass redact=False to include them (e.g. a
sale-records or registration packet). A header disclaimer rides every export so a
safety-critical number never leaves with its caveat stripped.
"""
from __future__ import annotations

from datetime import date as _date
from pathlib import Path

import redact as _redact

DISCLAIMER = ("_Generated by Garage. Informational only — not professional advice; "
              "verify safety-critical specs against the service manual or a technician. "
              "Estimated intervals are not the OEM schedule._")


def render_markdown(body_md: str, vehicle: dict, *, kind: str, title: str, redact: bool = True) -> str:
    """Render a self-contained Markdown export. Redacts VIN/plate unless redact=False."""
    forbidden = tuple(x for x in (vehicle.get("vin"), vehicle.get("plate")) if x)
    body = _redact.scrub(body_md, forbidden) if redact else body_md
    if redact:
        _redact.assert_no_pii(body, forbidden)  # structural backstop
    display = vehicle.get("display", "Vehicle")
    return (f"# {title}\n\n"
            f"**{display}** · {kind} · {_date.today().isoformat()}\n\n"
            f"{DISCLAIMER}\n\n---\n\n{body}\n")


def write_export(body_md: str, vehicle: dict, *, kind: str, title: str, out_dir,
                 redact: bool = True) -> Path:
    text = render_markdown(body_md, vehicle, kind=kind, title=title, redact=redact)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{vehicle.get('slug', 'vehicle')}-{kind}-{_date.today().isoformat()}.md"
    path.write_text(text)
    return path
